// Generated by services/zotero-core/scripts/generate-protocol.mjs. Do not edit.
export const SCHEMA_VERSION = 1;
export const PROTOCOL_VERSION = "1.0";
export const MAX_FRAME_BYTES = 1048576;
export const DEFAULT_DEADLINE_MS = 5000;
export const CAPABILITIES = Object.freeze([
  "attachment:read",
  "citation:read",
  "events:read",
  "library:read",
  "library:search",
  "library:write",
  "profile:read",
  "profile:write",
  "sync:read",
  "sync:write",
  "translation:read",
  "translation:write"
]);
export const METHOD_CAPABILITIES = Object.freeze({
  "attachment.close": "attachment:read",
  "attachment.open": "attachment:read",
  "attachment.read": "attachment:read",
  "citation.render": "citation:read",
  "citation.styles": "citation:read",
  "core.cancel": null,
  "core.events": "events:read",
  "core.handshake": null,
  "core.resume": null,
  "library.annotations": "library:read",
  "library.annotations-update": "library:write",
  "library.attachment": "library:read",
  "library.attachment-state": "library:read",
  "library.collection-mutate": "library:write",
  "library.collections": "library:read",
  "library.duplicates": "library:read",
  "library.feeds": "library:read",
  "library.fulltext-index": "library:write",
  "library.fulltext-search": "library:search",
  "library.item-children": "library:read",
  "library.item-facts": "library:read",
  "library.item-metadata": "library:read",
  "library.item-mutate": "library:write",
  "library.item-update": "library:write",
  "library.libraries": "library:read",
  "library.note": "library:read",
  "library.note-mutate": "library:write",
  "library.note-update": "library:write",
  "library.saved-search-items": "library:read",
  "library.saved-search-mutate": "library:write",
  "library.saved-searches": "library:read",
  "library.search": "library:search",
  "library.tags": "library:read",
  "profile.backup": "profile:write",
  "profile.migrate": "profile:write",
  "profile.status": "profile:read",
  "sync.conflicts": "sync:read",
  "sync.retry": "sync:write",
  "sync.status": "sync:read",
  "sync.storage-status": "sync:read",
  "translation.export": "translation:read",
  "translation.import": "translation:write",
  "translation.lookup": "translation:read",
  "translation.translators": "translation:read"
});
export const METHOD_TYPES = Object.freeze({
  "attachment.close": {
    "params": "AttachmentCloseParams",
    "result": "AttachmentCloseResult"
  },
  "attachment.open": {
    "params": "AttachmentOpenParams",
    "result": "AttachmentOpenResult"
  },
  "attachment.read": {
    "params": "AttachmentReadParams",
    "result": "AttachmentReadResult"
  },
  "citation.render": {
    "params": "CitationRenderParams",
    "result": "CitationRenderResult"
  },
  "citation.styles": {
    "params": "CitationStylesParams",
    "result": "CitationStylesResult"
  },
  "core.cancel": {
    "params": "CoreCancelParams",
    "result": "CoreCancelResult"
  },
  "core.events": {
    "params": "CoreEventsParams",
    "result": "CoreEventsResult"
  },
  "core.handshake": {
    "params": "CoreHandshakeParams",
    "result": "CoreHandshakeResult"
  },
  "core.resume": {
    "params": "CoreResumeParams",
    "result": "CoreResumeResult"
  },
  "library.annotations": {
    "params": "LibraryAnnotationsParams",
    "result": "LibraryAnnotationsResult"
  },
  "library.annotations-update": {
    "params": "LibraryAnnotationsUpdateParams",
    "result": "LibraryAnnotationsUpdateResult"
  },
  "library.attachment": {
    "params": "LibraryAttachmentParams",
    "result": "LibraryAttachmentSummary"
  },
  "library.attachment-state": {
    "params": "LibraryAttachmentParams",
    "result": "LibraryAttachmentState"
  },
  "library.collection-mutate": {
    "params": "LibraryCollectionMutationParams",
    "result": "LibraryCollectionMutationResult"
  },
  "library.collections": {
    "params": "LibraryCollectionsParams",
    "result": "LibraryCollectionsResult"
  },
  "library.duplicates": {
    "params": "LibraryDuplicatesParams",
    "result": "LibrarySearchResult"
  },
  "library.feeds": {
    "params": "LibraryFeedsParams",
    "result": "LibraryFeedsResult"
  },
  "library.fulltext-index": {
    "params": "LibraryFulltextIndexParams",
    "result": "LibraryFulltextIndexResult"
  },
  "library.fulltext-search": {
    "params": "LibraryFulltextSearchParams",
    "result": "LibraryFulltextSearchResult"
  },
  "library.item-children": {
    "params": "LibraryItemChildrenParams",
    "result": "LibraryItemChildrenResult"
  },
  "library.item-facts": {
    "params": "LibraryItemFactsParams",
    "result": "LibraryItemFacts"
  },
  "library.item-metadata": {
    "params": "LibraryItemMetadataParams",
    "result": "LibraryItemMetadata"
  },
  "library.item-mutate": {
    "params": "LibraryItemMutationParams",
    "result": "LibraryItemMutationResult"
  },
  "library.item-update": {
    "params": "LibraryItemUpdateParams",
    "result": "LibraryItemUpdateResult"
  },
  "library.libraries": {
    "params": "LibraryLibrariesParams",
    "result": "LibraryLibrariesResult"
  },
  "library.note": {
    "params": "LibraryNoteParams",
    "result": "LibraryNoteResult"
  },
  "library.note-mutate": {
    "params": "LibraryNoteMutationParams",
    "result": "LibraryNoteMutationResult"
  },
  "library.note-update": {
    "params": "LibraryNoteUpdateParams",
    "result": "LibraryNoteUpdateResult"
  },
  "library.saved-search-items": {
    "params": "LibrarySavedSearchItemsParams",
    "result": "LibrarySearchResult"
  },
  "library.saved-search-mutate": {
    "params": "LibrarySavedSearchMutationParams",
    "result": "LibrarySavedSearchMutationResult"
  },
  "library.saved-searches": {
    "params": "LibrarySavedSearchesParams",
    "result": "LibrarySavedSearchesResult"
  },
  "library.search": {
    "params": "LibrarySearchParams",
    "result": "LibrarySearchResult"
  },
  "library.tags": {
    "params": "LibraryTagsParams",
    "result": "LibraryTagsResult"
  },
  "profile.backup": {
    "params": "ProfileBackupParams",
    "result": "ProfileBackupResult"
  },
  "profile.migrate": {
    "params": "ProfileMigrateParams",
    "result": "ProfileMigrateResult"
  },
  "profile.status": {
    "params": "ProfileStatusParams",
    "result": "ProfileStatusResult"
  },
  "sync.conflicts": {
    "params": "SyncLibraryParams",
    "result": "SyncConflictsResult"
  },
  "sync.retry": {
    "params": "SyncRetryParams",
    "result": "SyncRetryResult"
  },
  "sync.status": {
    "params": "SyncStatusParams",
    "result": "SyncStatusResult"
  },
  "sync.storage-status": {
    "params": "SyncLibraryParams",
    "result": "SyncStorageStatusResult"
  },
  "translation.export": {
    "params": "TranslationExportParams",
    "result": "TranslationExportResult"
  },
  "translation.import": {
    "params": "TranslationImportParams",
    "result": "TranslationImportResult"
  },
  "translation.lookup": {
    "params": "TranslationLookupParams",
    "result": "TranslationLookupResult"
  },
  "translation.translators": {
    "params": "TranslationTranslatorsParams",
    "result": "TranslationTranslatorsResult"
  }
});
