// Generated by services/zotero-core/scripts/generate-protocol.mjs. Do not edit.
export const SCHEMA_VERSION = 1;
export const PROTOCOL_VERSION = "1.0";
export const MAX_FRAME_BYTES = 1048576;
export const DEFAULT_DEADLINE_MS = 5000;
export const CAPABILITIES = Object.freeze([
  "events:read",
  "library:read",
  "library:search",
  "profile:read"
]);
export const METHOD_CAPABILITIES = Object.freeze({
  "core.cancel": null,
  "core.handshake": null,
  "library.annotations": "library:read",
  "library.attachment": "library:read",
  "library.collections": "library:read",
  "library.item-children": "library:read",
  "library.note": "library:read",
  "library.search": "library:search",
  "profile.status": "profile:read"
});
export const METHOD_TYPES = Object.freeze({
  "core.cancel": {
    "params": "CoreCancelParams",
    "result": "CoreCancelResult"
  },
  "core.handshake": {
    "params": "CoreHandshakeParams",
    "result": "CoreHandshakeResult"
  },
  "library.annotations": {
    "params": "LibraryAnnotationsParams",
    "result": "LibraryAnnotationsResult"
  },
  "library.attachment": {
    "params": "LibraryAttachmentParams",
    "result": "LibraryAttachmentSummary"
  },
  "library.collections": {
    "params": "LibraryCollectionsParams",
    "result": "LibraryCollectionsResult"
  },
  "library.item-children": {
    "params": "LibraryItemChildrenParams",
    "result": "LibraryItemChildrenResult"
  },
  "library.note": {
    "params": "LibraryNoteParams",
    "result": "LibraryNoteResult"
  },
  "library.search": {
    "params": "LibrarySearchParams",
    "result": "LibrarySearchResult"
  },
  "profile.status": {
    "params": "ProfileStatusParams",
    "result": "ProfileStatusResult"
  }
});
