import { mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

const runtimeArtifact = (product) => `// This file is generated by scripts/chatero/generate-product.mjs. Do not edit.\nexport const CHATERO_PRODUCT = Object.freeze(${JSON.stringify(product, null, 2)});\n`;

const shellArtifact = (product) => `# This file is generated by scripts/chatero/generate-product.mjs. Do not edit.\nAPP_NAME=${JSON.stringify(product.displayName)}\nAPP_ID=${JSON.stringify(product.applicationID)}\nAPP_BUNDLE_ID=${JSON.stringify(product.bundleID)}\nAPP_URL_SCHEME=${JSON.stringify(product.externalURLScheme)}\nSIGN=0\n`;

export async function generateProduct({ root = repositoryRoot, check = false } = {}) {
  const product = JSON.parse(await readFile(resolve(root, "app/chatero-product.json"), "utf8"));
  const artifacts = new Map([
    [resolve(root, "resource/chatero-product.mjs"), runtimeArtifact(product)],
    [resolve(root, "app/chatero-product.sh"), shellArtifact(product)]
  ]);

  for (const [path, content] of artifacts) {
    let current;
    try {
      current = await readFile(path, "utf8");
    }
    catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
    if (check) {
      if (current !== content) throw new Error(`stale generated artifact: ${path}`);
      continue;
    }
    if (current !== content) {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, content);
    }
  }

  return product;
}

const run = async () => {
  let root = repositoryRoot;
  let check = false;
  for (let index = 2; index < process.argv.length; index++) {
    if (process.argv[index] === "--check") {
      check = true;
    }
    else if (process.argv[index] === "--root") {
      root = resolve(process.argv[++index]);
    }
    else {
      throw new Error(`unknown argument: ${process.argv[index]}`);
    }
  }
  await generateProduct({ root, check });
};

if (process.argv[1] && basename(process.argv[1]) === "generate-product.mjs") {
  run().catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
