import { mkdir, readFile, writeFile } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import { basename, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

const runtimeArtifact = (product) => `// This file is generated by scripts/chatero/generate-product.mjs. Do not edit.\nexport const CHATERO_PRODUCT = Object.freeze(${JSON.stringify(product, null, 2)});\n`;

const shellArtifact = (product) => `# This file is generated by scripts/chatero/generate-product.mjs. Do not edit.\nAPP_NAME=${JSON.stringify(product.displayName)}\nAPP_ID=${JSON.stringify(product.applicationID)}\nAPP_BUNDLE_ID=${JSON.stringify(product.bundleID)}\nAPP_URL_SCHEME=${JSON.stringify(product.externalURLScheme)}\nUPSTREAM_BASE=${JSON.stringify(product.upstreamBase)}\nSIGN=0\n`;

const buildArtifact = ({ sourceCommit, upstreamBase }) => `// This file is generated by scripts/chatero/generate-product.mjs. Do not edit.\nexport const CHATERO_BUILD = Object.freeze(${JSON.stringify({ sourceCommit, upstreamBase }, null, 2)});\n`;

export async function generateProduct({
  root = repositoryRoot,
  check = false,
  buildProvenance = false,
  sourceCommit
} = {}) {
  const product = JSON.parse(await readFile(resolve(root, "app/chatero-product.json"), "utf8"));
  const artifacts = new Map([
    [resolve(root, "resource/chatero-product.mjs"), runtimeArtifact(product)],
    [resolve(root, "app/chatero-product.sh"), shellArtifact(product)]
  ]);

  if (buildProvenance) {
    sourceCommit ??= execFileSync("git", ["-C", root, "rev-parse", "HEAD"], {
      encoding: "utf8"
    }).trim();
    if (!/^[0-9a-f]{40}$/.test(sourceCommit)) {
      throw new Error(`invalid source commit: ${sourceCommit}`);
    }
    if (!/^[0-9a-f]{40}$/.test(product.upstreamBase)) {
      throw new Error(`invalid upstream base: ${product.upstreamBase}`);
    }
    artifacts.set(
      resolve(root, "resource/chatero-build.mjs"),
      buildArtifact({ sourceCommit, upstreamBase: product.upstreamBase })
    );
  }

  for (const [path, content] of artifacts) {
    let current;
    try {
      current = await readFile(path, "utf8");
    }
    catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
    if (check) {
      if (current !== content) throw new Error(`stale generated artifact: ${path}`);
      continue;
    }
    if (current !== content) {
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, content);
    }
  }

  return product;
}

const run = async () => {
  let root = repositoryRoot;
  let check = false;
  let buildProvenance = false;
  let sourceCommit;
  for (let index = 2; index < process.argv.length; index++) {
    if (process.argv[index] === "--check") {
      check = true;
    }
    else if (process.argv[index] === "--build-provenance") {
      buildProvenance = true;
    }
    else if (process.argv[index] === "--source-commit") {
      sourceCommit = process.argv[++index];
    }
    else if (process.argv[index] === "--root") {
      root = resolve(process.argv[++index]);
    }
    else {
      throw new Error(`unknown argument: ${process.argv[index]}`);
    }
  }
  await generateProduct({ root, check, buildProvenance, sourceCommit });
};

if (process.argv[1] && basename(process.argv[1]) === "generate-product.mjs") {
  run().catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
